// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCollection(arg1:main.Collection):Promise<void>;

export function CreateCommand(arg1:main.Command):Promise<void>;

export function CreateTag(arg1:main.Tag):Promise<void>;

export function DeleteCollection(arg1:number):Promise<void>;

export function DeleteCommand(arg1:number):Promise<void>;

export function DeleteTag(arg1:number):Promise<void>;

export function GetCollection(arg1:number):Promise<main.Collection>;

export function GetCommand(arg1:number):Promise<main.Command>;

export function GetCommandsByCollectionID(arg1:main.Option):Promise<Array<main.Command>>;

export function GetCommandsByTagId(arg1:main.Option):Promise<Array<main.Command>>;

export function GetMenuItems():Promise<Record<string, any>>;

export function GetOptions(arg1:main.Option):Promise<main.Response>;

export function GetStatus():Promise<main.Status>;

export function GetTag(arg1:number):Promise<main.Tag>;

export function UpdateCollection(arg1:main.Collection):Promise<void>;

export function UpdateCommand(arg1:main.Command):Promise<void>;

export function UpdateTag(arg1:main.Tag):Promise<void>;
