// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMenuItems():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;
