// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateCommand(arg1) {
  return window['go']['main']['App']['CreateCommand'](arg1);
}

export function CreateTag(arg1) {
  return window['go']['main']['App']['CreateTag'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteCommand(arg1) {
  return window['go']['main']['App']['DeleteCommand'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function GetCollection(arg1) {
  return window['go']['main']['App']['GetCollection'](arg1);
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetCommand(arg1) {
  return window['go']['main']['App']['GetCommand'](arg1);
}

export function GetCommands() {
  return window['go']['main']['App']['GetCommands']();
}

export function GetCommandsByCollectionID(arg1) {
  return window['go']['main']['App']['GetCommandsByCollectionID'](arg1);
}

export function GetCommandsByTagID(arg1) {
  return window['go']['main']['App']['GetCommandsByTagID'](arg1);
}

export function GetMenuItems() {
  return window['go']['main']['App']['GetMenuItems']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTag(arg1) {
  return window['go']['main']['App']['GetTag'](arg1);
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function UpdateCollection(arg1) {
  return window['go']['main']['App']['UpdateCollection'](arg1);
}

export function UpdateCommand(arg1) {
  return window['go']['main']['App']['UpdateCommand'](arg1);
}

export function UpdateTag(arg1) {
  return window['go']['main']['App']['UpdateTag'](arg1);
}
