// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCollection(arg1:main.Collection):Promise<void>;

export function CreateCommand(arg1:main.Command):Promise<void>;

export function CreateTag(arg1:main.Tag):Promise<void>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteCommand(arg1:string):Promise<void>;

export function DeleteTag(arg1:string):Promise<void>;

export function GetCollection(arg1:string):Promise<main.Collection>;

export function GetCollections():Promise<Array<main.Collection>>;

export function GetCollectionsOptions(arg1:main.Option):Promise<Array<main.Collection>>;

export function GetCommand(arg1:string):Promise<main.Command>;

export function GetCommands():Promise<Array<main.Command>>;

export function GetCommandsByCollectionID(arg1:string):Promise<Array<main.Command>>;

export function GetCommandsByTagID(arg1:string):Promise<Array<main.Command>>;

export function GetCommandsOptions(arg1:main.Option):Promise<Array<main.Command>>;

export function GetMenuItems():Promise<Record<string, any>>;

export function GetStatus():Promise<main.Status>;

export function GetTag(arg1:string):Promise<main.Tag>;

export function GetTags():Promise<Array<main.Tag>>;

export function GetTagsOptions(arg1:main.Option):Promise<Array<main.Tag>>;

export function UpdateCollection(arg1:main.Collection):Promise<void>;

export function UpdateCommand(arg1:main.Command):Promise<void>;

export function UpdateTag(arg1:main.Tag):Promise<void>;
